# Generated by Django 3.1.5 on 2021-01-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addons',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='addons',
            name='payment_information',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='addons',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cashier Check', "Cashier's Check"), ('Credit Card', 'Credit Card'), ('Direct Deposit', 'Direct Deposit'), ('Electronic Payment', 'Electronic Payment'), ('Money Order', 'Money Order')], max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='addons',
            name='addon_type',
            field=models.CharField(choices=[('Comment', 'Comment'), ('Update', 'Update'), ('Add Parts', 'Add Parts'), ('Add Work', 'Add Work'), ('Request', 'Request'), ('Reply', 'Reply'), ('Approve', 'Approve Request'), ('Refuse', 'Refuse Request'), ('Payment', 'Payment')], max_length=32),
        ),
        migrations.AlterField(
            model_name='addons',
            name='repair_status_previous',
            field=models.CharField(choices=[('Submitted', 'Submitted for Approval'), ('Approved', 'Approved by Repairer'), ('Canceled', 'Canceled by Customer'), ('Declined', 'Declined by Repairer'), ('Scheduled Pickup', 'Pickup is Scheduled'), ('Scheduled House Call', 'House Call is Scheduled'), ('Retrieved', 'Picked Up by Repairer'), ('Started Repair', 'Started Repair'), ('Finished Repair', 'Finished Repair'), ('Timing Out', 'Adjusting Time Accuracy'), ('Scheduled Delivery', 'Delivery is Scheduled'), ('Delivered', 'Delivered by Repairer'), ('Paid in Full', 'Paid in Full'), ('Partial Payment', 'Partial Payment')], default='Submitted', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='addons',
            name='repair_status_update',
            field=models.CharField(choices=[('Submitted', 'Submitted for Approval'), ('Approved', 'Approved by Repairer'), ('Canceled', 'Canceled by Customer'), ('Declined', 'Declined by Repairer'), ('Scheduled Pickup', 'Pickup is Scheduled'), ('Scheduled House Call', 'House Call is Scheduled'), ('Retrieved', 'Picked Up by Repairer'), ('Started Repair', 'Started Repair'), ('Finished Repair', 'Finished Repair'), ('Timing Out', 'Adjusting Time Accuracy'), ('Scheduled Delivery', 'Delivery is Scheduled'), ('Delivered', 'Delivered by Repairer'), ('Paid in Full', 'Paid in Full'), ('Partial Payment', 'Partial Payment')], default='Submitted', max_length=32),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='repair_status',
            field=models.CharField(choices=[('Submitted', 'Submitted for Approval'), ('Approved', 'Approved by Repairer'), ('Canceled', 'Canceled by Customer'), ('Declined', 'Declined by Repairer'), ('Scheduled Pickup', 'Pickup is Scheduled'), ('Scheduled House Call', 'House Call is Scheduled'), ('Retrieved', 'Picked Up by Repairer'), ('Started Repair', 'Started Repair'), ('Finished Repair', 'Finished Repair'), ('Timing Out', 'Adjusting Time Accuracy'), ('Scheduled Delivery', 'Delivery is Scheduled'), ('Delivered', 'Delivered by Repairer'), ('Paid in Full', 'Paid in Full'), ('Partial Payment', 'Partial Payment')], default='Submitted', max_length=32),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='repair_type',
            field=models.CharField(choices=[('Service Call', 'Service/House Call'), ('Regulate', 'Regulate Time'), ('Get Working', 'Adjust/Get Working'), ('Replace Parts', 'Add/Replace Parts'), ('Refurbish Quartz', 'Refurbish/Replace Battery Movement'), ('Refurbish Electric', 'Refurbish/Replace Electric Movement'), ('Refurbish Mechanical', 'Refurbish Mechanical Movement'), ('Mechanical to Quartz', 'Replace Mechanical Movement with Battery Movement'), ('Prepair to Move', 'Prepair Grandfather Clock for Move/Shipment'), ('Move Grandfather', 'Move Grandfather Clock Fron One Address To Another Address')], help_text="Note: 'Clean & Overhaul' refers to the complete restoration of the clock's mechanical mechanism", max_length=32),
        ),
    ]
