# Generated by Django 3.1.5 on 2021-01-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_auto_20210129_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='repair_type',
            field=models.CharField(choices=[('House Call', 'House Call'), ('Refurbish Mechanical', 'Clean / Overhaul Mechanical Clock'), ('Refurbish Quartz', 'Refurbish / Replace Battery Movement'), ('Refurbish Electric', 'Refurbish / Replace Electric Movement'), ('Get Working', 'Adjust / Get Working'), ('Replace Parts', 'Add / Replace Parts'), ('Mechanical to Quartz', 'Replace Mechanical Movement w/ Battery Movement'), ('Regulate', 'Regulate Time'), ('Prepair to Move', 'Prepair Grandfather Clock for Move / Shipping'), ('Move Grandfather', 'Move Grandfather Clock fron one Address to Another')], help_text="Note: 'Clean & Overhaul' refers to the complete restoration of the clock's mechanical mechanism", max_length=32),
        ),
    ]
