# Generated by Django 3.1.5 on 2021-01-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_auto_20210110_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date_paid',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
