# Generated by Django 3.1.5 on 2021-01-13 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_auto_20210113_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='date_last_updated',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
