# Generated by Django 3.1.5 on 2021-01-14 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0003_workorder_date_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='addons',
            name='user_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
