# Generated by Django 3.1.5 on 2021-01-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0003_auto_20210111_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addons',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='workorders/addons/'),
        ),
        migrations.AlterField(
            model_name='addons',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='workorders/addons/'),
        ),
        migrations.AlterField(
            model_name='addons',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='workorders/addons/'),
        ),
        migrations.AlterField(
            model_name='addons',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='workorders/addons/'),
        ),
        migrations.AlterField(
            model_name='addons',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='workorders/addons/'),
        ),
    ]
