# Generated by Django 3.1.5 on 2021-01-15 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('workorder', '0004_addons_user_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addons',
            name='user_fk',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='user_fk',
        ),
        migrations.AddField(
            model_name='addons',
            name='added_by',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Repairer', 'Repairer')], default='Repairer', max_length=8),
        ),
        migrations.AddField(
            model_name='addons',
            name='repair_status_previous',
            field=models.CharField(default='Submitted', editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer_fk',
            field=models.ForeignKey(default='4fc6c448-532b-4949-b4be-faa39a0d90e1', on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer'),
        ),
    ]
