# Generated by Django 3.1.5 on 2021-01-15 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repairer', '0001_initial'),
        ('customer', '0001_initial'),
        ('clock', '0010_auto_20210114_2354'),
        ('workorder', '0005_auto_20210114_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addons',
            name='workorder_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='clock_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clock.clock'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='customer_fk',
            field=models.ForeignKey(default='4fc6c448-532b-4949-b4be-faa39a0d90e1', on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='repairer_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repairer.repairer'),
        ),
    ]
