# Generated by Django 3.1.5 on 2021-01-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0006_auto_20210114_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addons',
            name='repair_status_previous',
            field=models.CharField(choices=[('Submitted', 'Submitted for Approval'), ('Approved', 'Approved by Repairer'), ('Canceled', 'Canceled by Customer'), ('Declined', 'Declined by Repairer'), ('Scheduled Pickup', 'Pickup is Scheduled'), ('Retrieved', 'Picked Up by Repairer'), ('Started Repair', 'Started Repair'), ('Finished Repair', 'Finished Repair'), ('Timing Out', 'Adjusting Time Accuracy'), ('Scheduled Delivery', 'Delivery is Scheduled'), ('Delivered', 'Delivered by Repairer'), ('Paid in Full', 'Paid in Full')], default='Submitted', editable=False, max_length=32),
        ),
    ]
