# Generated by Django 3.1.5 on 2021-01-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='battery_count',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5+')], default=0, help_text='How many batteries does your clock take?'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='chime_count',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Chime'), (1, 'Single Chime'), (2, 'Dual Chime'), (3, 'Triple Chime'), (4, '4+ Chime Options')], default=3, help_text='(Note: Chimes usually ring every quarter) | Chime count indicates how many different chime options your clock has. Some have none, others only Westminster, and some Grandfather clocks have, say: Westminster, Whittenauer, and Saint Michael; battery/quartz clocks can have 3-4+ chime optons'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='choices_are_locked',
            field=models.BooleanField(default=False, help_text='(Note: Customer can only change their clock information when True)'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='dial_diameter_centimeters',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='(Note: Dial diameter is only import for large battery operated clocks)'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='drive_type',
            field=models.CharField(choices=[('Mainspring', 'Mainspring - Wind Up'), ('Chain', 'Weights on Chains'), ('Cable', 'Weights on Cable with Pullies'), ('String', 'Weights on String'), ('Atmospheric', 'Atmospheric'), ('Electric', 'Electric'), ('Quartz', 'Battery/Quartz')], default='Cable', help_text='Drive type is what powers the clock', max_length=16),
        ),
        migrations.AlterField(
            model_name='clock',
            name='gear_material',
            field=models.CharField(choices=[('Metal', 'Metal Gears'), ('Wood', 'Wooden Gears'), ('Plastic', 'Plastic Gears')], default='Metal', help_text='For battery clocks choose "Plastic" for most others choos "Metal"', max_length=16),
        ),
        migrations.AlterField(
            model_name='clock',
            name='has_activity_other',
            field=models.BooleanField(default=False, help_text='Select if your Cuckoo clock has features such as dancing wheel and/or any other moving features on its face'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='has_alarm',
            field=models.BooleanField(default=False, help_text='Select if your clock has an alarm feature. (Mostly for quartz/battery, Kitchen clocks, and Alarm clocks)'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='has_calendar',
            field=models.BooleanField(default=False, help_text='If you are unsure, leave this field as is.  The Repairer will understand and set it correctly'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='has_glass_over_face',
            field=models.BooleanField(default=False, help_text='(Note: Has glass over face is only import for large battery operated clocks)'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='has_light',
            field=models.BooleanField(default=False, help_text='Select if your clock has a light'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='has_moon_dial',
            field=models.BooleanField(default=False, help_text='If you are unsure, leave this field as is.  The Repairer will understand and set it correctly'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='has_music_box',
            field=models.BooleanField(default=False, help_text='Select if your Cuckoo clock has a music box'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='has_off_at_night',
            field=models.BooleanField(default=False, help_text='If you are unsure, leave this field as is.  The Repairer will understand and set it correctly'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='has_pendulum',
            field=models.BooleanField(default=False, help_text='Select if your clock has a Pendulum'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='has_second_hand',
            field=models.BooleanField(default=False, help_text='Select if your clock has a second hand'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='has_self_adjusting_beat',
            field=models.BooleanField(default=False, help_text='Leave this field as is.  The Repairer will understand and set it correctly'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='has_self_adjusting_strike',
            field=models.BooleanField(default=False, help_text='Leave this field as is.  The Repairer will understand and set it correctly'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='has_tubes',
            field=models.BooleanField(default=False, help_text='Only Tubular Grandfather clocks have this rare and expensive feature.  Such clocks have 5 to 9 tubes that hang down nearly the full height of the clock.  The are usually about 10 to 15 centimiters in diameter.'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Please add at least one picture of this clock', upload_to='clocks/'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='nickname',
            field=models.CharField(default='Nickname', help_text='Please choose a Nickname to identify this clock', max_length=32),
        ),
        migrations.AlterField(
            model_name='clock',
            name='strike_type',
            field=models.CharField(choices=[('None', 'No Strike'), ('Bim-Bam', 'Bim-Bam'), ('Cuckoo', 'Cuckoo'), ('Chord', 'Hourly Chord'), ('Note', 'Hourly Note'), ('Ship', "Ship's Bells")], default='Chord', help_text='(Note: Strike is hourly) | If the clock hammer strikes a coil/bell/rod then it is a "Note," if two or more rods it is a "Chord"', max_length=32),
        ),
        migrations.AlterField(
            model_name='clock',
            name='train_count',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='How many places the clock winds (i.e., if you wind it in two place your clock has a train count of 2)'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='tube_count',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Zero'), (5, 'Five Tubes'), (9, 'Nine Tubes')], default=0, help_text='If your clock "Has tubes" then count them and enter the total number of Tubes here.'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='wind_interval_days',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Never - Quartz/Battery/Electric/Atmos'), (1, 'Once Every Day'), (8, 'Once Every Week'), (15, 'Once Every Other Week'), (31, 'Once Every Month'), (400, 'Once Every Year')], default=8, help_text='How often do you have to wind this clock?'),
        ),
    ]
