# Generated by Django 3.1.4 on 2020-12-30 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clock',
            name='clock_type',
        ),
        migrations.RemoveField(
            model_name='clock',
            name='customer_fk',
        ),
        migrations.AddField(
            model_name='clock',
            name='user_fk',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
