# Generated by Django 3.1.4 on 2021-01-01 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='user_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clock',
            name='wind_interval_days',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Never'), (1, 'Once Every Day'), (8, 'Once Every Week'), (15, 'Once Every Other Week'), (31, 'Once Every Month'), (400, 'Once Every Year')], default=8),
        ),
    ]
