# Generated by Django 3.1.5 on 2021-01-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocktypes',
            name='chime_count',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Chime'), (1, 'Single Chime'), (2, 'Dual Chime'), (3, 'Triple Chime'), (4, '4+ Chime Options')], default=0),
        ),
        migrations.AlterField(
            model_name='clocktypes',
            name='clock_type',
            field=models.CharField(choices=[('Advertising', 'Advertising'), ('Animated', 'Animated'), ('Anniversary', 'Anniversary'), ('Atmos', 'Atmos'), ('Balloon', 'Balloon'), ('Banjo', 'Banjo'), ('Beehive', 'Beehive'), ('Black Mantel', 'Black Mantel'), ('Blinking Eye', 'Blinking Eye'), ('Calendar', 'Calendar'), ('Carriage', 'Carriage'), ('China/Porcelain', 'China/Porcelain'), ('Column', 'Column'), ('Crystal Regulator', 'Crystal Regulator'), ('Cuckoo', 'Cuckoo'), ('Desk', 'Desk'), ('Dial', 'Dial'), ('Drop Trunk/Schoolhouse', 'Drop Trunk/Schoolhouse'), ('Figural', 'Figural'), ('Garnitures', 'Garnitures'), ('Gothic', 'Gothic'), ('Kitchen', 'Kitchen'), ('Lantern', 'Lantern'), ('Longcase/Grandfather', 'Longcase/Grandfather'), ('Lyre', 'Lyre'), ('Mantel', 'Mantel/Shelf'), ('Mission', 'Mission'), ('Mystery', 'Mystery'), ('Novelty', 'Novelty'), ('Novelty-Quartz', 'Novelty-Quartz'), ('Novelty-Electric', 'Novelty-Electric'), ('Novelty-Mechanical', 'Novelty-Mechanical'), ('Ogee', 'Ogee'), ('Picture', 'Picture'), ('Portico', 'Portico'), ('Pillar & Scroll', 'Pillar & Scroll'), ('Plato', 'Plato'), ("Ship's", "Ship's"), ('Skeleton', 'Skeleton'), ('Steeple', 'Steeple'), ('Swinging', 'Swinging'), ('Tambour', 'Tambour'), ('Tape', 'Tape'), ('Vienna Regulator', 'Vienna Regulator'), ('Wag on the Wall', 'Wag on the Wall'), ('Wall', 'Wall')], default='Mantel', max_length=32),
        ),
        migrations.AlterField(
            model_name='clocktypes',
            name='drive_type',
            field=models.CharField(choices=[('Mainspring', 'Mainspring - Wind Up'), ('Chain', 'Weights on Chains'), ('Cable', 'Weights on Cable with Pullies'), ('String', 'Weights on String'), ('Atmospheric', 'Atmospheric'), ('Electric', 'Electric'), ('Quartz', 'Battery/Quartz')], default='Mainspring', max_length=16),
        ),
        migrations.AlterField(
            model_name='clocktypes',
            name='footprint',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Floor', 'Floor'), ('Mantel', 'Mantel'), ('Wall', 'Wall')], default='Mantel', max_length=16),
        ),
        migrations.AlterField(
            model_name='clocktypes',
            name='strike_type',
            field=models.CharField(choices=[('None', 'No Strike'), ('Bim-Bam', 'Bim-Bam'), ('Cuckoo', 'Cuckoo'), ('Chord', 'Hourly Chord'), ('Note', 'Hourly Note'), ('Ship', "Ship's Bells")], default='None', max_length=32),
        ),
        migrations.AlterField(
            model_name='clocktypes',
            name='train_count',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
