# Generated by Django 3.1.4 on 2021-01-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0002_auto_20210101_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='nickname',
            field=models.CharField(default='Nickname', max_length=32),
        ),
    ]
