# Generated by Django 3.1.5 on 2021-01-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0003_auto_20210106_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='strike_type',
            field=models.CharField(choices=[('None', 'No Strike'), ('Bim-Bam', 'Bim-Bam'), ('Cuckoo', 'Cuckoo'), ('Chord', 'Hourly Chord'), ('Note', 'Hourly Note'), ('Ship', "Ship's Bells")], default='Chord', max_length=32),
        ),
    ]
