# Generated by Django 3.1.5 on 2021-01-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0004_auto_20210111_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='clocktypes',
            name='has_half_hour_strike',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clock',
            name='footprint',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Floor', 'Floor'), ('Mantel', 'Mantel'), ('Wall', 'Wall')], default='Floor', max_length=16),
        ),
        migrations.AlterField(
            model_name='clock',
            name='tube_count',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Zero'), (4, 'Four Tubes'), (5, 'Five Tubes'), (9, 'Nine Tubes')], default=0, help_text='If your clock "Has tubes" then count them and enter the total number of Tubes here.'),
        ),
        migrations.AlterField(
            model_name='clocktypes',
            name='clock_type',
            field=models.CharField(choices=[('Advertising', 'Advertising'), ('Animated', 'Animated'), ('Anniversary', 'Anniversary'), ('Atmos', 'Atmos'), ('Balloon', 'Balloon'), ('Banjo', 'Banjo'), ('Beehive', 'Beehive'), ('Black Mantel', 'Black Mantel'), ('Blinking Eye', 'Blinking Eye'), ('Calendar', 'Calendar'), ('Carriage', 'Carriage'), ('China/Porcelain', 'China/Porcelain'), ('Column', 'Column'), ('Crystal Regulator', 'Crystal Regulator'), ('Cuckoo', 'Cuckoo'), ('Desk', 'Desk'), ('Dial', 'Dial'), ('Drop Dial/Schoolhouse', 'Drop Dial/Schoolhouse'), ('Figural', 'Figural'), ('Garnitures', 'Garnitures'), ('Gothic', 'Gothic'), ('Kitchen', 'Kitchen'), ('Lantern', 'Lantern'), ('Longcase/Grandfather', 'Grandfather/Grandmother'), ('Lyre', 'Lyre'), ('Mantel', 'Mantel'), ('Mission', 'Mission'), ('Mystery', 'Mystery'), ('Novelty', 'Novelty'), ('Novelty-Quartz', 'Novelty-Quartz'), ('Novelty-Electric', 'Novelty-Electric'), ('Novelty-Mechanical', 'Novelty-Mechanical'), ('Ogee', 'Ogee'), ('Picture', 'Picture'), ('Portico', 'Portico'), ('Pillar & Scroll', 'Pillar & Scroll'), ('Plato', 'Plato'), ("Ship's", "Ship's"), ('Skeleton', 'Skeleton'), ('Steeple', 'Steeple'), ('Swinging', 'Swinging'), ('Tambour', 'Tambour'), ('Tape', 'Tape'), ('Vienna Regulator', 'Vienna Regulator'), ('Wag on the Wall', 'Wag on the Wall'), ('Wall', 'Wall')], default='Longcase/Grandfather', max_length=32),
        ),
        migrations.AlterField(
            model_name='clocktypes',
            name='footprint',
            field=models.CharField(choices=[('Desktop', 'Desktop'), ('Floor', 'Floor'), ('Mantel', 'Mantel'), ('Wall', 'Wall')], default='Floor', max_length=16),
        ),
        migrations.AlterField(
            model_name='clocktypes',
            name='tube_count',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Zero'), (4, 'Four Tubes'), (5, 'Five Tubes'), (9, 'Nine Tubes')], default=0),
        ),
    ]
