# Generated by Django 3.1.4 on 2021-01-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0004_auto_20210103_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='battery_count',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5+')], default=0),
        ),
        migrations.AddField(
            model_name='clock',
            name='dial_diameter_millimeters',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='clock',
            name='has_glass_over_face',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clock',
            name='has_light',
            field=models.BooleanField(default=False),
        ),
    ]
