# Generated by Django 3.1.5 on 2021-01-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0004_auto_20210109_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='pics/'),
        ),
    ]
