# Generated by Django 3.1.5 on 2021-01-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0006_auto_20210112_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='has_half_hour_strike',
            field=models.BooleanField(default=False),
        ),
    ]
