# Generated by Django 3.1.5 on 2021-01-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0007_clock_has_half_hour_strike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='has_half_hour_strike',
            field=models.BooleanField(default=False, help_text='Select if this clock strikes on both the hour and the half your'),
        ),
    ]
