# Generated by Django 3.1.5 on 2021-01-15 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0009_auto_20210114_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='clock_type_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clock.clocktypes'),
        ),
    ]
