# Generated by Django 3.1.5 on 2021-01-15 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('clock', '0010_auto_20210114_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='customer_fk',
            field=models.ForeignKey(default='4fc6c448-532b-4949-b4be-faa39a0d90e1', on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
