# Generated by Django 3.1.5 on 2021-01-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0011_auto_20210114_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='nickname',
            field=models.CharField(default='Nickname', help_text='Please choose a Nickname to identify this clock', max_length=64),
        ),
    ]
