version: '3.8'
volumes:
  # PostGIS DB - New 20201231
  postgis-data:
#  dbbackups:

  # PostgreSQL DB - Original form "book" app tutorial
  # postgres_data:
  
services:
  web:
    build: .
    # HTTP
#    command: python /code/manage.py runserver 0.0.0.0:8000
    # HTTS
    command: python /code/manage.py runsslserver 0.0.0.0:8000
#    command: gunicorn config.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      # NOTE: Any dollar signs '$' need to be escaped with an additional dollar sign '$$'
      - "DJANGO_SECRET_KEY=gl0s1f=_+29rg35vqjc)pvg+zagv#!jsb(2^@!_rm%w-ycx&e&"
      # NON-Production, Debug Settings...
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"

      - "DJANGO_ADMIN_URL=admin/"

      # Amazon's (AWS) Simple Email Service Settings
      - "EMAIL_HOST_KEY=email-smtp.us-east-2.amazonaws.com"
      - "EMAIL_HOST_USER_KEY=AKIA257AFI4BPCQFC226"
      - "EMAIL_HOST_PASSWORD_KEY=BMXGG2uyy+Zv4DYI0e4Ou4DoaAUhgFy284qsADju4cak"
      - "EMAIL_PORT_KEY=25"
      - "EMAIL_USE_TLS_KEY=True"

      # If you need to create multiple database you can add comma separated databases eg gis,data
      - "POSTGRES_DB=gis"
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASS=docker"
      - "ALLOW_IP_RANGE=0.0.0.0/0"
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - "POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting"

      # PostgreSQL DB - Original form "book" app tutorial
  # db:
  #   image: postgres:11
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - "POSTGRES_HOST_AUTH_METHOD=trust"
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASS=postgres
  #     - ALLOW_IP_RANGE=0.0.0.0/0

  # PostGIS DB - New 20201231
  db:
    image: kartoza/postgis:12.0
    volumes:
      - postgis-data:/var/lib/postgresql
#      - dbbackups:/backups
    # environment:
      # # If you need to create multiple database you can add comma separated databases eg gis,data
      # - "POSTGRES_DB=gis"
      # - "POSTGRES_USER=docker"
      # - "POSTGRES_PASS=docker"
      # - "ALLOW_IP_RANGE=0.0.0.0/0"
      # # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      # - "POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting"
    ports:
      - 25432:5432
#     - 5432
    restart: on-failure
    healthcheck:
      test: "exit 0"

  # dbbackups:
  #   image: kartoza/pg-backup:12.0
  #   hostname: pg-backups
  #   volumes:
  #     - dbbackups:/backups
  #   environment:
  #     - DUMPPREFIX=PG_db
  #     - POSTGRES_USER=docker
  #     - POSTGRES_PASS=docker
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_HOST=db
  #     - POSTGRES_DBNAME=gis
  #   restart: on-failure
  #   depends_on:
  #     db:
  #       condition: service_healthy
