# Generated by Django 3.1.5 on 2021-01-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='hide_my_address',
            field=models.BooleanField(default=False, help_text='Select to prevent repairers from seeing your full address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='hide_my_email',
            field=models.BooleanField(default=False, help_text='Select to prevent repairers from seeing your email address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='hide_my_phone',
            field=models.BooleanField(default=False, help_text='Select to prevent repairers from seeing your telephone number'),
        ),
    ]
