# Generated by Django 3.1.4 on 2021-01-02 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210101_2226'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customer_id_index',
        ),
    ]
