# Generated by Django 3.1.4 on 2021-01-04 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clocktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('clock_type', models.CharField(choices=[('Advertising', 'Advertising'), ('Animated', 'Animated'), ('Anniversary', 'Anniversary'), ('Atmos', 'Atmos'), ('Balloon', 'Balloon'), ('Banjo', 'Banjo'), ('Beehive', 'Beehive'), ('Black Mantel', 'Black Mantel'), ('Blinking Eye', 'Blinking Eye'), ('Calendar', 'Calendar'), ('Carriage', 'Carriage'), ('China/Porcelain', 'China/Porcelain'), ('Column', 'Column'), ('Crystal Regulator', 'Crystal Regulator'), ('Cuckoo', 'Cuckoo'), ('Dial', 'Dial'), ('Drop Trunk/School House', 'Drop Trunk/School House'), ('Figural', 'Figural'), ('Garnitures', 'Garnitures'), ('Gothic', 'Gothic'), ('Kitchen', 'Kitchen'), ('Lantern', 'Lantern'), ('Longcase/Grandfather', 'Longcase/Grandfather'), ('Lyre', 'Lyre'), ('Mission', 'Mission'), ('Mystery', 'Mystery'), ('Novelty', 'Novelty'), ('Ogee', 'Ogee'), ('Picture', 'Picture'), ('Portico', 'Portico'), ('Pillar & Scroll', 'Pillar & Scroll'), ('Plato', 'Plato'), ('Shelf', 'Shelf'), ("Ship's", "Ship's"), ('Skeleton', 'Skeleton'), ('Steeple', 'Steeple'), ('Swinging', 'Swinging'), ('Tambour', 'Tambour'), ('Tape', 'Tape'), ('Vienna Regulator', 'Vienna Regulator'), ('Wag on the Wall', 'Wag on the Wall'), ('Wall', 'Wall')], default='Longcase/Grandfather', max_length=32)),
                ('footprint', models.CharField(choices=[('Desktop', 'Desktop'), ('Floor', 'Floor'), ('Mantle', 'Mantle'), ('Wall', 'Wall')], default='Floor', max_length=16)),
                ('dial_diameter_millimeters', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('has_glass_over_face', models.BooleanField(default=False)),
                ('train_count', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('wind_interval_days', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Never - Quartz/Battery/Atmos'), (1, 'Once Every Day'), (8, 'Once Every Week'), (15, 'Once Every Other Week'), (31, 'Once Every Month'), (400, 'Once Every Year')], default=8)),
                ('drive_type', models.CharField(choices=[('Mainspring', 'Mainspring - Wind Up'), ('Chain', 'Weights on Chains'), ('Cable', 'Weights on Cable with Pullies'), ('String', 'Weights on String'), ('Atmospheric', 'Atmospheric'), ('Electric', 'Electric'), ('Quartz', 'Battery/Quartz')], default='Cable', max_length=16)),
                ('gear_material', models.CharField(choices=[('Metal', 'Metal Gears'), ('Wood', 'Wooden Gears'), ('Plastic', 'Plastic Gears')], default='Metal', max_length=16)),
                ('chime_count', models.PositiveSmallIntegerField(choices=[(0, 'No Chime'), (1, 'Single Chime'), (2, 'Dual Chime'), (3, 'Triple Chime'), (4, '4+ Chime Options')], default=3)),
                ('strike_type', models.CharField(choices=[('None', 'No Strike'), ('Bim-Bam', 'Bim-Bam'), ('Note', 'Hourly Note'), ('Chord', 'Hourly Chord')], default='Chord', max_length=32)),
                ('has_pendulum', models.BooleanField(default=False)),
                ('has_self_adjusting_beat', models.BooleanField(default=False)),
                ('has_self_adjusting_strike', models.BooleanField(default=False)),
                ('has_second_hand', models.BooleanField(default=False)),
                ('has_off_at_night', models.BooleanField(default=False)),
                ('has_calendar', models.BooleanField(default=False)),
                ('has_moon_dial', models.BooleanField(default=False)),
                ('has_alarm', models.BooleanField(default=False)),
                ('has_music_box', models.BooleanField(default=False)),
                ('has_activity_other', models.BooleanField(default=False)),
                ('has_light', models.BooleanField(default=False)),
                ('battery_count', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5+')], default=0)),
                ('has_tubes', models.BooleanField(default=False)),
                ('tube_count', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Zero'), (5, 'Five Tubes'), (9, 'Nine Tubes')], default=0)),
                ('choices_are_locked', models.BooleanField(default=False)),
                ('image_1', models.ImageField(blank=True, upload_to='clock_pics/')),
                ('image_2', models.ImageField(blank=True, upload_to='clock_pics/')),
                ('image_3', models.ImageField(blank=True, upload_to='clock_pics/')),
                ('image_4', models.ImageField(blank=True, upload_to='clock_pics/')),
                ('image_5', models.ImageField(blank=True, upload_to='clock_pics/')),
            ],
        ),
        migrations.AddIndex(
            model_name='clocktype',
            index=models.Index(fields=['id'], name='clocktype_id_index'),
        ),
    ]
