# Generated by Django 3.1.4 on 2021-01-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocktype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocktype',
            name='wind_interval_days',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Never'), (1, 'Once Every Day'), (8, 'Once Every Week'), (15, 'Once Every Other Week'), (31, 'Once Every Month'), (400, 'Once Every Year')], default=8),
        ),
    ]
