# Generated by Django 3.1.5 on 2021-01-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocktype', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clocktype',
            old_name='dial_diameter_millimeters',
            new_name='dial_diameter_centimeter',
        ),
        migrations.AlterField(
            model_name='clocktype',
            name='wind_interval_days',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Never - Quartz/Battery/Electric/Atmos'), (1, 'Once Every Day'), (8, 'Once Every Week'), (15, 'Once Every Other Week'), (31, 'Once Every Month'), (400, 'Once Every Year')], default=8),
        ),
    ]
