# Generated by Django 3.1.4 on 2021-01-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocktype', '0002_auto_20210101_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='clocktype',
            name='battery_count',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5+')], default=0),
        ),
        migrations.AddField(
            model_name='clocktype',
            name='dial_diameter_millimeters',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='clocktype',
            name='has_glass_over_face',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clocktype',
            name='has_light',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clocktype',
            name='drive_type',
            field=models.CharField(choices=[('Mainspring', 'Mainspring - Wind Up'), ('Chain', 'Weights on Chains'), ('Cable', 'Weights on Cable with Pullies'), ('String', 'Weights on String'), ('Atmospheric', 'Atmospheric'), ('Electric', 'Electric'), ('Quartz', 'Battery/Quartz')], default='Cable', max_length=16),
        ),
        migrations.AlterField(
            model_name='clocktype',
            name='gear_material',
            field=models.CharField(choices=[('Metal', 'Metal Gears'), ('Wood', 'Wooden Gears'), ('Plastic', 'Plastic Gears')], default='Metal', max_length=16),
        ),
        migrations.AlterField(
            model_name='clocktype',
            name='wind_interval_days',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Never - Quartz/Battery/Atmos'), (1, 'Once Every Day'), (8, 'Once Every Week'), (15, 'Once Every Other Week'), (31, 'Once Every Month'), (400, 'Once Every Year')], default=8),
        ),
    ]
