# Generated by Django 3.1.5 on 2021-01-07 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clocktype', '0002_auto_20210106_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clocktype',
            old_name='dial_diameter_centimeter',
            new_name='dial_diameter_centimeters',
        ),
    ]
