# Generated by Django 3.1.5 on 2021-01-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocktype', '0003_auto_20210106_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocktype',
            name='strike_type',
            field=models.CharField(choices=[('None', 'No Strike'), ('Bim-Bam', 'Bim-Bam'), ('Cuckoo', 'Cuckoo'), ('Note', 'Hourly Note'), ('Chord', 'Hourly Chord')], default='Chord', max_length=32),
        ),
    ]
