# Generated by Django 3.1.5 on 2021-01-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocktype', '0006_auto_20210110_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clocktype',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='clocks/types/'),
        ),
        migrations.AlterField(
            model_name='clocktype',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='clocks/types/'),
        ),
        migrations.AlterField(
            model_name='clocktype',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='clocks/types/'),
        ),
        migrations.AlterField(
            model_name='clocktype',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='clocks/types/'),
        ),
        migrations.AlterField(
            model_name='clocktype',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='clocks/types/'),
        ),
    ]
