# Generated by Django 3.1.5 on 2021-01-17 01:53

import datetime
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('nickname', models.CharField(max_length=64)),
                ('contact_name', models.CharField(max_length=128)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(help_text='Street number and streed address', max_length=64)),
                ('address_other', models.CharField(blank=True, help_text='Apartment / Unit / Suite / Etc.', max_length=16)),
                ('locality_disctrict', models.CharField(blank=True, help_text='Disctrict / Arrondissements', max_length=64)),
                ('place_city', models.CharField(help_text='City / Village / Municipality', max_length=64)),
                ('district_prefectures', models.CharField(blank=True, help_text='Prefectures', max_length=64)),
                ('region_state', models.CharField(blank=True, help_text='State / Province', max_length=64)),
                ('postcode', models.CharField(blank=True, help_text='Zipcode / Postal Code', max_length=12)),
                ('country', models.CharField(max_length=64)),
                ('latitude', models.FloatField(default=42.95, help_text='Only set manually if the latitude decimal number is known')),
                ('longitude', models.FloatField(default=-83.64, help_text='Only set manually if the longitude decimal number is known')),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326)),
                ('relevance', models.FloatField(blank=True, default=0, help_text='Do not edit: Mapbox specific field')),
                ('accuracy', models.CharField(blank=True, help_text='Do not edit: Mapbox specific field', max_length=16)),
                ('person_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
    ]
