# Generated by Django 3.1.5 on 2021-01-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_primary',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Billing', 'Billing'), ('Pickup', 'Pickup'), ('Delivery', 'Delivery'), ('Other', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
